server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ok
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

mybatis:
  type-aliases-package: com.example.demo.entity
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:mapping/*.xml


logging:
  level:
    com:
      example:
        demo:
          dao:  debug

